package com.company;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class leetcode {
    public static void main(String[] args) {
        List<String> list = new ArrayList<>(Arrays.asList("Minimum Number of Operations to Move All Balls to Each Box",
                "Partition Array According to Given Pivot",
                "Find the Prefix Common Array of Two Arrays",
                "Reverse Odd Levels of Binary Tree",
                "Queries on Number of Points Inside a Circle",
                "Rearrange Array Elements by Sign",
                "Arithmetic Subarrays",
                "Recover a Tree From Preorder Traversal",
                "Reveal Cards In Increasing Order",
                "Find the Punishment Number of an Integer",
                "Permutations",
                "Minimum Operations to Make Binary Array Elements Equal to One I",
                "Design a Stack With Increment Operation",
                "Find Unique Binary String",
                "Check if Number is a Sum of Powers of Three",
                "Lowest Common Ancestor of Deepest Leaves",
                "Painting a Grid With Three Different Colors",
                "Apply Substitutions",
                "Remove All Occurrences of a Substring",
                "Construct Quad Tree",
                "Find All Duplicates in an Array",
                "Lexicographical Numbers",
                "Count Complete Subarrays in an Array",
                "Find All Groups of Farmland",
                "Kth Smallest Element in a BST",
                "Remove Nodes From Linked List",
                "Queue Reconstruction by Height",
                "Design Underground System",
                "Count Servers that Communicate",
                "Insert into a Binary Search Tree",
                "Count Number of Nice Subarrays",
                "Construct the Lexicographically Largest Valid Sequence",
                "Combinations",
                "Search in a Sorted Array of Unknown Size",
                "Put Marbles in Bags",
                "Capacity To Ship Packages Within D Days",
                "Stone Game",
                "Maximum Absolute Sum of Any Subarray",
                "Construct String With Repeat Limit",
                "Sum of Beauty of All Substrings",
                "Binary Tree Level Order Traversal",
                "Number of Enclaves",
                "Split Linked List in Parts",
                "Tuple with Same Product",
                "Find Kth Bit in Nth Binary String",
                "Find the Count of Good Integers",
                "Flip Equivalent Binary Trees",
                "The kth Factor of n",
                "Count Subarrays With Fixed Bounds",
                "Design Hit Counter",
                "Find Minimum Time to Reach Last Room II",
                "Minimum Cost Walk in Weighted Graph",
                "Swapping Nodes in a Linked List",
                "Flatten Binary Tree to Linked List",
                "Check if Grid can be Cut into Sections",
                "Serialize and Deserialize N-ary Tree",
                "Path with Maximum Gold",
                "Delete Nodes From Linked List Present in Array",
                "Peak Index in a Mountain Array",
                "Minimum Operations to Make a Uni-Value Grid",
                "Minimum Cost For Tickets",
                "Divide Nodes Into the Maximum Number of Groups",
                "Swap Nodes in Pairs",
                "Bitwise XOR of All Pairings",
                "Construct Binary Tree from Preorder and Inorder Traversal",
                "All Nodes Distance K in Binary Tree",
                "Next Greater Element II",
                "Count the Number of Good Subarrays",
                "Construct Binary Tree from Inorder and Postorder Traversal",
                "Max Sum of a Pair With Equal Sum of Digits",
                "Binary Subarrays With Sum",
                "The Earliest Moment When Everyone Become Friends",
                "Print Binary Tree",
                "Nested List Weight Sum II",
                "Shortest Path Visiting All Nodes",
                "Sequential Digits",
                "Flatten Nested List Iterator",
                "Single Number II",
                "House Robber IV",
                "Search Suggestions System",
                "Longest Nice Subarray",
                "Minimum Swaps to Make Strings Equal",
                "Find Score of an Array After Marking All Elements",
                "Convert Sorted List to Binary Search Tree",
                "Design File System",
                "Longest Palindromic Subsequence",
                "Max Chunks To Make Sorted",
                "Linked List Random Node",
                "First Completely Painted Row or Column",
                "Find the Smallest Divisor Given a Threshold",
                "Special Binary String",
                "Evaluate Division",
                "Longest Repeating Substring",
                "Remove Duplicates from Sorted Array II",
                "Find the Duplicate Number",
                "Product of the Last K Numbers",
                "Best Sightseeing Pair",
                "Minimize XOR",
                "Reorder List",
                "Last Day Where You Can Still Cross",
                "Next Greater Node In Linked List",
                "Number of Distinct Islands",
                "Valid Sudoku",
                "Maximum Employees to Be Invited to a Meeting",
                "Minimum Cost to Cut a Stick",
                "Binary Tree Zigzag Level Order Traversal",
                "Task Scheduler",
                "Path With Minimum Effort",
                "Shortest Common Supersequence",
                "Burst Balloons",
                "Knight Dialer",
                "Integer Break",
                "Decode String",
                "Grid Game",
                "Minimum Moves to Equal Array Elements II",
                "Smallest String Starting From Leaf",
                "Open the Lock",
                "Minimum Number of Arrows to Burst Balloons",
                "Solving Questions With Brainpower",
                "Sum of Subarray Ranges",
                "Maximum Height by Stacking Cuboids",
                "Minimum Time to Repair Cars",
                "Remove All Adjacent Duplicates in String II",
                "Maximum Number of Points From Grid Queries",
                "Smallest String With Swaps",
                "Rank Teams by Votes",
                "Triangle",
                "Partition List",
                "Serialize and Deserialize Binary Tree",
                "Trapping Rain Water II",
                "Edit Distance",
                "Shortest Bridge",
                "Sender With Largest Word Count",
                "Rabbits in Forest",
                "Champagne Tower",
                "Total Characters in String After Transformations II",
                "Continuous Subarrays",
                "Longest Increasing Subsequence",
                "Critical Connections in a Network",
                "Combination Sum II",
                "Pacific Atlantic Water Flow",
                "Count Number of Homogenous Substrings",
                "Design a Number Container System",
                "Count Univalue Subtrees",
                "Longest Repeating Character Replacement",
                "Binary Tree Vertical Order Traversal",
                "Number of Ways to Form a Target String Given a Dictionary",
                "Hand of Straights",
                "Move Pieces to Obtain a String",
                "Sort an Array",
                "Maximum Value of an Ordered Triplet II",
                "Count Good Numbers",
                "Minimum Domino Rotations For Equal Row",
                "Range Sum Query 2D - Immutable",
                "Find All Possible Recipes from Given Supplies",
                "Insertion Sort List",
                "Distribute Candies Among Children II",
                "Recover Binary Search Tree",
                "Reorganize String",
                "Number of Ways to Split Array",
                "Student Attendance Record II",
                "Find Minimum Time to Reach Last Room I",
                "Word Subsets",
                "Minimum Area Rectangle II",
                "Subarray Sums Divisible by K",
                "Minimum Array End",
                "Zero Array Transformation III",
                "Minimum Genetic Mutation",
                "Non-overlapping Intervals",
                "Meeting Scheduler",
                "House Robber III",
                "Linked List Cycle II",
                "Number of Distinct Islands II",
                "Maximum XOR With an Element From Array",
                "Path Existence Queries in a Graph I",
                "Combination Sum IV",
                "Longest Arithmetic Subsequence of Given Difference",
                "Zero Array Transformation I",
                "Count Number of Bad Pairs",
                "Count Numbers with Unique Digits",
                "Find the Number of Distinct Colors Among the Balls",
                "Apply Operations to Maximize Score",
                "Path With Maximum Minimum Value",
                "Spiral Matrix",
                "Longest Palindrome by Concatenating Two Letter Words",
                "Sum of Two Integers",
                "Car Fleet",
                "Android Unlock Patterns",
                "Shifting Letters II",
                "Minimum Replacements to Sort the Array",
                "Maximum XOR of Two Numbers in an Array",
                "Find a Peak Element II",
                "Count the Number of Fair Pairs",
                "Find Closest Node to Given Two Nodes",
                "Basic Calculator III",
                "Minimum Interval to Include Each Query",
                "Search a 2D Matrix",
                "Find All Anagrams in a String",
                "Domino and Tromino Tiling",
                "Maximum Swap",
                "Shortest Subarray to be Removed to Make Array Sorted",
                "01 Matrix",
                "Check if There is a Path With Equal Number of 0's And 1's",
                "Find And Replace in String",
                "Detect Squares",
                "Repeated DNA Sequences",
                "Lexicographically Minimum String After Removing Stars",
                "Minimum Number of Taps to Open to Water a Garden",
                "Furthest Building You Can Reach",
                "Minimum Equal Sum of Two Arrays After Replacing Zeros",
                "Maximum Candies Allocated to K Children",
                "Distinct Subsequences",
                "Optimal Account Balancing",
                "Maximum Area Rectangle With Point Constraints I",
                "Reverse Linked List II",
                "Count Number of Balanced Permutations",
                "Longest Arithmetic Subsequence",
                "Time Taken to Cross the Door",
                "Design Search Autocomplete System",
                "Time Based Key-Value Store",
                "Minimum Size Subarray Sum",
                "Graph Valid Tree",
                "Ugly Number II",
                "Detonate the Maximum Bombs",
                "Largest Divisible Subset",
                "Find the Celebrity",
                "Partition Equal Subset Sum",
                "Find the Safest Path in a Grid",
                "Design In-Memory File System",
                "Text Justification",
                "Count Days Without Meetings",
                "Snakes and Ladders",
                "K-th Symbol in Grammar",
                "Permutation in String",
                "Design Add and Search Words Data Structure",
                "Best Time to Buy and Sell Stock IV",
                "Bus Routes",
                "3Sum Closest",
                "Count the Number of Powerful Integers",
                "LFU Cache",
                "Single-Threaded CPU",
                "Expressive Words",
                "Maximum Difference Between Even and Odd Frequency II",
                "Check If Array Pairs Are Divisible by k",
                "K-th Smallest in Lexicographical Order",
                "Implement Rand10() Using Rand7()",
                "Basic Calculator II",
                "Minimum Operations to Exceed Threshold Value II",
                "Shortest Path in a Grid with Obstacles Elimination",
                "Basic Calculator",
                "UTF-8 Validation",
                "Longest Substring with At Least K Repeating Characters",
                "Sum of Mutated Array Closest to Target",
                "Word Search",
                "Check if a Parentheses String Can Be Valid",
                "K-diff Pairs in an Array",
                "Find the Shortest Superstring",
                "Range Module",
                "Race Car",
                "Maximum Width of Binary Tree",
                "Frequency of the Most Frequent Element",
                "The Skyline Problem",
                "Zero Array Transformation II",
                "House Robber II",
                "Water and Jug Problem",
                "Rotate Array",
                "Read N Characters Given read4 II - Call Multiple Times",
                "Minimize the Maximum Edge Weight of Graph",
                "Design Excel Sum Formula",
                "Design Twitter",
                "Super Washing Machines",
                "Multiply Strings",
                "Minimum Time to Finish the Race",
                "Scramble String",
                "Minimum Height Trees",
                "Rank Transform of a Matrix",
                "Longest Mountain in Array",
                "Find K Pairs with Smallest Sums",
                "Shortest Palindrome",
                "Find Original Array From Doubled Array",
                "Find in Mountain Array",
                "Prefix and Suffix Search",
                "H-Index",
                "Number of Islands II",
                "Minimum Operations to Reduce X to Zero",
                "Get the Maximum Score",
                "Remove Comments",
                "Maximum Score of a Node Sequence",
                "Search in Rotated Sorted Array II",
                "Maximum Value at a Given Index in a Bounded Array",
                "Minimum Weighted Subgraph With the Required Paths",
                "Finding MK Average",
                "4Sum",
                "Partition to K Equal Sum Subsets",
                "Separate Squares I",
                "Guess the Word",
                "Best Time to Buy and Sell Stock V",
                "Sum of Subarray Minimums",
                "Number of Ways to Arrive at Destination",
                "Swap Adjacent in LR String",
                "Sum of Square Numbers",
                "Escape the Spreading Fire",
                "Number of Digit One",
                "Insert Delete GetRandom O(1) - Duplicates allowed",
                "Nth Digit",
                "Identify the Largest Outlier in an Array",
                "Super Pow",
                "Maximum Product Subarray",
                "Verbal Arithmetic Puzzle",
                "Count Primes",
                "Find the Divisibility Array of a String",
                "Next Greater Element III",
                "Design Task Manager",
                "Ways to Split Array Into Three Subarrays",
                "Manhattan Distances of All Arrangements of Pieces",
                "Substring with Concatenation of All Words",
                "Maximum Number of Events That Can Be Attended",
                "Additive Number",
                "Reach End of Array With Max Score",
                "Create Maximum Number",
                "Find the String with LCP",
                "Maximum Number of Distinct Elements After Operations",
                "Longest Duplicate Substring",
                "Can I Win",
                "Wildcard Matching",
                "Sum of Good Subsequences",
                "Zero Array Transformation IV",
                "Sequence Reconstruction",
                "Regular Expression Matching",
                "Max Points on a Line",
                "Count Special Subsequences",
                "The Latest Time to Catch a Bus",
                "Merge Operations for Minimum Travel Time",
                "Movement of Robots",
                "Fraction to Recurring Decimal",
                "Maximum Frequency After Subarray Operation",
                "Longest Increasing Subsequence II",
                "Count the Number of Square-Free Subsets",
                "Walking Robot Simulation II",
                "Minimum Number of Flips to Make Binary Grid Palindromic II",
                "Find the Minimum Cost Array Permutation",
                "Maximum Coins From K Consecutive Bags",
                "Partition Array Into Two Arrays to Minimize Sum Difference",
                "Maximum Frequency of an Element After Performing Operations I",
                "Count Non-Decreasing Subarrays After K Operations",
                "Maximize Subarray Sum After Removing All Occurrences of One Element",
                "Separate Squares II",
                "Divide Two Integers",
                "Find the Occurrence of First Almost Equal Substring"
        ));


    }
}
